version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pumplord_mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-app}

volumes:
  mongo_data:
